name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag zach27/atut-bootcamp:v1
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        ecr: auto
        logout: true
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Extract metadata (labels, tags, etc.) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: zach27/atut-bootcamp:v0
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
          context: .
          file: ./Dockerfile
          push: true
          tags: zach27/atut-bootcamp:v1
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
      runs-on: ubuntu-latest
      needs: [push-python-app]
      steps:
        - name: Deploy app
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.GR_TEST_HOST }}
            username: ${{ secrets.GR_TEST_USER }}
            key: ${{ secrets.GR_TEST_SSH_KEY }}
            port: ${{ secrets.SSH_PORT }}
            # stop, remove and update step by step
            script: |
            
              cd leisure-experience-app
              docker-compose -f docker-compose.test.yml down
              docker load < django.tar
              docker load < nextjs.tar
              COMPOSE_HTTP_TIMEOUT=200 docker-compose -f docker-compose.test.yml up -d      